// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PedidosGraphQL.Api.Data;

#nullable disable

namespace PedidosGraphQL.Api.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    partial class PedidosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PedidosGraphQL.Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Ana García",
                            Estado = 2,
                            FechaPedido = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 129.90m
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "Luis Martínez",
                            Estado = 1,
                            FechaPedido = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 59.50m
                        },
                        new
                        {
                            Id = 3,
                            Cliente = "Marta Sánchez",
                            Estado = 0,
                            FechaPedido = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 340.00m
                        },
                        new
                        {
                            Id = 4,
                            Cliente = "Carlos Ruiz",
                            Estado = 3,
                            FechaPedido = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 89.99m
                        },
                        new
                        {
                            Id = 5,
                            Cliente = "Elena Torres",
                            Estado = 0,
                            FechaPedido = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Total = 210.25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
